# Global
alias ll='ls -alh --color'
alias cs='./vendor/bin/php-cs-fixer fix --verbose --diff --show-progress=dots'
alias psalm='./vendor/bin/psalm'
alias rector='./vendor/bin/rector'

# Symfony
alias sf='bin/console'
alias sfcc='sf cache:clear'
alias sfmi='sf do:mi:mi'
alias sfdoex='sf do:mi:ex'
alias sfdiff='sf do:mi:diff'

alias sfdropdb='sf do:da:drop --if-exists --force'
alias sfcreatedb='sf do:da:cr --if-not-exists --no-interaction'
