name: CI/CD Twittix API

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y  

      - name: Build Docker Compose services
        run: docker-compose build  

      - name: Ensure Docker network exists
        run: |
          docker network inspect net-twittix >/dev/null 2>&1 || docker network create net-twittix

      - name: Run Docker Compose services
        run: docker-compose up -d

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, opcache, bcmath
      
      - name: Run quality checks
        run: |
          docker compose exec php sh -c "
            composer install && \
            php ./vendor/bin/rector process src --dry-run --verbose && \
            php ./vendor/bin/php-cs-fixer fix --verbose --show-progress=dots && \
            php ./vendor/bin/psalm && \
            php ./bin/console doctrine:database:create --if-not-exists && \
            php ./bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration && \
            php ./bin/console doctrine:schema:validate && \
            php ./bin/console doctrine:fixtures:load --no-interaction --append
          "    
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          # Paramètres pour la connexion SSH
          SSH_PRIVATE_KEY: ${{ secrets.DEV_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.DEV_SERVER_IP }}
          REMOTE_USER: ${{ secrets.DEV_HOST }}
          TARGET: ./dev/api/
          SCRIPT_AFTER: |
            cd ./dev/api/ 
            docker network inspect net-twittix >/dev/null 2>&1 || docker network create net-twittix
            docker compose exec php sh -c "
              composer install && \
              php ./vendor/bin/rector process src --dry-run --verbose && \
              php ./vendor/bin/php-cs-fixer fix --verbose --show-progress=dots && \
              php ./vendor/bin/psalm && \
              php ./bin/console doctrine:database:create --if-not-exists && \
              php ./bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration && \
              php ./bin/console doctrine:schema:validate && \
              php ./bin/console doctrine:fixtures:load --no-interaction
            "    