name: CI/CD Twittix API

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y  

      - name: Build Docker Compose services
        run: docker-compose build  

      - name: Run Docker Compose services
        run: docker-compose up -d

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, opcache, bcmath
      
      - name: Run quality checks
        run: |
          docker compose exec php sh -c "
            composer install && \
            php ./vendor/bin/rector process src --dry-run --verbose && \
            php ./vendor/bin/php-cs-fixer fix --verbose --show-progress=dots && \
            php ./vendor/bin/psalm && \
            php ./bin/console doctrine:database:create --if-not-exists && \
            php ./bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration && \
            php ./bin/console doctrine:schema:validate && \
            php ./bin/console doctrine:fixtures:load --no-interaction --append
          "    

    build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/php/
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/twittix-front-user:latest
